version: 1.0.{build}

branches:
  only:
    - master
  except:
    - gh-pages

# Do not build on tags (GitHub and BitBucket)
skip_tags: false

#---------------------------------#
#    environment configuration    #
#---------------------------------#
image: Visual Studio 2015
os: Visual Studio 2015

environment:
  Configuration: Release
  matrix:
  - TARGET: i686-pc-windows-msvc
    ARCH: x86
    WIN_SDK_VERSION: v7.0
    VS: C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\vcvarsall.bat

#---------------------------------#
#       build configuration       #
#---------------------------------#

platform: x86

build: off
build_script:
  - "where bash"
  - ps: .\build.ps1

#---------------------------------#
#       tests configuration       #
#---------------------------------#

test: off

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
  - path: '**\nginx.exe'

deploy:
  release: nginx-v$(appveyor_build_version)
  description: 'Release description'
  provider: GitHub
  auth_token:
    secure: 7vPd3RxHe/SekGhE4AC5FSLBl9EdGigpz+CzEKLkikWkFo1axvgv5Iql4AR+4722
  artifact: /.*\.nginx\.exe/
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true 