version: 1.0.{build}

branches:
  only:
    - master
  except:
    - gh-pages

# Do not build on tags (GitHub and BitBucket)
skip_tags: false

#---------------------------------#
#    environment configuration    #
#---------------------------------#
image: Visual Studio 2017 RC
os: Visual Studio 2017 RC

environment:
  Configuration: Release
  matrix:
  - TARGET: msvc-2017
    VS: 2017
  - TARGET: msvc-2015
    VS: 2015
  - TARGET: msvc-2013
    VS: 2013
  - TARGET: msvc-2010
    VS: 2010
  - TARGET: msvc-2008
    VS: 2008

#---------------------------------#
#       build configuration       #
#---------------------------------#

platform: x86

install:
  - ps: Get-PackageProvider -Name NuGet -Force
  - ps: Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
  - ps: install-module pscx

build: off
build_script:
  - ps: .\build.ps1

#---------------------------------#
#       tests configuration       #
#---------------------------------#

test: off

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
  - path: '**\nginx**.zip'

deploy:
  release: $(appveyor_repo_tag_name)
  description: 'Release description'
  provider: GitHub
  auth_token:
    secure: 7vPd3RxHe/SekGhE4AC5FSLBl9EdGigpz+CzEKLkikWkFo1axvgv5Iql4AR+4722
  artifact: /.*\.nginx.*\.zip/
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true 
